[workspace]
members = [
    "xpath",
    "xpath_unit_tests",
    "test_packages/xpath_test_fnabs",
    "test_packages/xpath_test_fnceiling",
    "test_packages/xpath_test_fnday_from_datetime",
    "test_packages/xpath_test_fnfloor",
    "test_packages/xpath_test_fnhours_from_datetime",
    "test_packages/xpath_test_fnminutes_from_datetime",
    "test_packages/xpath_test_fnmonth_from_datetime",
    "test_packages/xpath_test_fnnot",
    "test_packages/xpath_test_fnround",
    "test_packages/xpath_test_fnseconds_from_datetime",
    "test_packages/xpath_test_fnyear_from_datetime",
    "test_packages/xpath_test_opboolean_equal",
    "test_packages/xpath_test_opdatetime_equal",
    "test_packages/xpath_test_opdatetime_greater_than",
    "test_packages/xpath_test_opdatetime_less_than",
    "test_packages/xpath_test_opnumeric_add",
    "test_packages/xpath_test_opnumeric_add_double",
    "test_packages/xpath_test_opnumeric_add_float",
    "test_packages/xpath_test_opnumeric_divide",
    "test_packages/xpath_test_opnumeric_divide_double",
    "test_packages/xpath_test_opnumeric_divide_float",
    "test_packages/xpath_test_opnumeric_equal",
    "test_packages/xpath_test_opnumeric_equal_double",
    "test_packages/xpath_test_opnumeric_equal_float",
    "test_packages/xpath_test_opnumeric_greater_than",
    "test_packages/xpath_test_opnumeric_greater_than_double",
    "test_packages/xpath_test_opnumeric_greater_than_float",
    "test_packages/xpath_test_opnumeric_integer_divide",
    "test_packages/xpath_test_opnumeric_less_than",
    "test_packages/xpath_test_opnumeric_less_than_double",
    "test_packages/xpath_test_opnumeric_less_than_float",
    "test_packages/xpath_test_opnumeric_mod",
    "test_packages/xpath_test_opnumeric_multiply",
    "test_packages/xpath_test_opnumeric_multiply_double",
    "test_packages/xpath_test_opnumeric_multiply_float",
    "test_packages/xpath_test_opnumeric_subtract",
    "test_packages/xpath_test_opnumeric_subtract_double",
    "test_packages/xpath_test_opnumeric_subtract_float",
    "test_packages/xpath_test_xsdouble_from_int",
    "test_packages/xpath_test_xsfloat_from_double",
    "test_packages/xpath_test_xsfloat_from_int",
    "test_packages/xpath_test_xsinteger_from_double",
    "test_packages/xpath_test_xsinteger_from_float",
]
