[package]
name = "xpath"
type = "lib"
authors = ["jeswr"]

[dependencies]
ieee754 = { tag = "v0.1.0", git = "https://github.com/jeswr/noir_IEEE754", directory = "ieee754" }
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
