[package]
name = "xpath"
type = "lib"
authors = ["jeswr"]

[dependencies]
ieee754 = { tag = "v0.1.0", git = "https://github.com/jeswr/noir_IEEE754", directory = "ieee754" }
string_utils = { tag = "main", git = "https://github.com/madztheo/noir-string-utils.git" }
